In [3]:
import numpy as np

In [12]:
a = np.random.randint(1,100,[3,5])
b = np.random.randint(1,100,[3,5])
print(a)
print(b)

[[72 45 61 46 14]
 [35 30 13 23 86]
 [27 72 60 57 11]]
[[43 71 85 65 11]
 [70 56  8 57  5]
 [84 57 34 71 30]]


In [39]:
a+b  


array([[115, 116, 146, 111,  25],
       [105,  86,  21,  80,  91],
       [111, 129,  94, 128,  41]], dtype=int32)

In [38]:
np.concatenate([a,b])


array([[72, 45, 61, 46, 14],
       [35, 30, 13, 23, 86],
       [27, 72, 60, 57, 11],
       [43, 71, 85, 65, 11],
       [70, 56,  8, 57,  5],
       [84, 57, 34, 71, 30]], dtype=int32)

In [37]:
np.append(a,b)


array([72, 45, 61, 46, 14, 35, 30, 13, 23, 86, 27, 72, 60, 57, 11, 43, 71,
       85, 65, 11, 70, 56,  8, 57,  5, 84, 57, 34, 71, 30], dtype=int32)

In [36]:
np.concatenate([a,b],axis=0)   # axis = 0 열방향 , axis = 1  행방향


array([[72, 45, 61, 46, 14],
       [35, 30, 13, 23, 86],
       [27, 72, 60, 57, 11],
       [43, 71, 85, 65, 11],
       [70, 56,  8, 57,  5],
       [84, 57, 34, 71, 30]], dtype=int32)

In [34]:
np.split(a,3)  # 2차원행렬   [[a],[b],[c]]를   [[a]],[[b]],[[c]] 로 



[array([[72, 45, 61, 46, 14]], dtype=int32),
 array([[35, 30, 13, 23, 86]], dtype=int32),
 array([[27, 72, 60, 57, 11]], dtype=int32)]

In [35]:
np.array_split(a,2)  # 2개의 배열로 (알아서)



[array([[72, 45, 61, 46, 14],
        [35, 30, 13, 23, 86]], dtype=int32),
 array([[27, 72, 60, 57, 11]], dtype=int32)]