In [2]:
import numpy as np

In [17]:
a = np.random.randint(1,11,[2,3])
b = np.random.randint(1,11,[2,3])
print(a)
print(b)

[[10 10  6]
 [ 1  4  9]]
[[ 4  6  2]
 [ 8 10  9]]


In [21]:
a+b
 

array([[14, 16,  8],
       [ 9, 14, 18]], dtype=int32)

In [22]:
np.add(a,b)

array([[14, 16,  8],
       [ 9, 14, 18]], dtype=int32)

In [15]:
np.subtract(a,b)   # 빼기

array([[-6, -1,  3],
       [-4,  5, -2]], dtype=int32)

In [13]:
np.divide(a,b) # 나누기

array([[0.33333333, 0.5       , 1.42857143],
       [0.2       , 3.5       , 0.66666667]])

In [14]:
np.multiply(a,b) # 곱하기

array([[27,  2, 70],
       [ 5, 14, 24]], dtype=int32)

In [16]:
np.mod(a,b) # 나눈 나머지 구하기

array([[3, 1, 3],
       [1, 1, 4]], dtype=int32)

In [18]:
np.power(a,b) 

array([[    10000,   1000000,        36],
       [        1,   1048576, 387420489]], dtype=int32)

In [20]:
np.less_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [41]:
# 연습문제
name = np.array(['홍길동','김길동','이길동'])
kor = np.array([100,90,85])
eng = np.array([10,50,20])
mat = np.array([40,60,55])

print(name[np.greater(np.divide(np.add(np.add(kor,eng),mat),len(name)),60)])
print(name[(kor+eng+mat)/len(name)>60])

['김길동']
['김길동']


In [43]:
a = np.random.rand(2,3)
np.ceil(a) # 올림

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.floor(a) # 버림

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.rint(a) #반올림

array([[0., 0., 1.],
       [1., 0., 1.]])

In [46]:
np.round(a,2) #자리수 지정 반올림

array([[0.15, 0.23, 0.88],
       [0.96, 0.11, 0.75]])

In [57]:
a = np.random.rand(2,3)
print(a)

f = np.ceil(a*10)/10  # 소숫점 두번째부터 올리는 방법
print(f)


[[0.23043279 0.85600052 0.54966529]
 [0.26767518 0.11769756 0.69562029]]
[[0.2 0.9 0.5]
 [0.3 0.1 0.7]]
[[0.3 0.9 0.6]
 [0.3 0.2 0.7]]


In [61]:
np.array([1,np.nan,2,np.inf,3])  #nan = 값이 없음    inf=값이 무한대

array([ 1., nan,  2., inf,  3.])

In [68]:
h = np.random.randint(-5,6,[2,3])
print(h)

[[ 1  3 -4]
 [ 4  3 -1]]


In [69]:
np.abs(h)

array([[1, 3, 4],
       [4, 3, 1]], dtype=int32)

In [70]:
np.sqrt(h)

C:\Users\soldesk\AppData\Local\Temp\ipykernel_12388\2970498925.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(h)


array([[1.        , 1.73205081,        nan],
       [2.        , 1.73205081,        nan]])