In [3]:
import numpy as np

행렬의 모든 합

In [8]:
a = np.random.randint(1,10,[2,3])
print(a)
b = np.sum(a)
print(b)

[[6 1 3]
 [8 3 3]]
24


행렬의 모든 퍙균

In [9]:
c =np.mean(a)
print(c)

4.0


분산 : 평균에서 얼마나 퍼졌나
표준편차

In [15]:
d = a - c  # 각 값에서 평균을 뺌(값이랑 평균이랑 얼마나 차이나나)
print(d)


[[ 2. -3. -1.]
 [ 4. -1. -1.]]


In [16]:
print(np.sum(d)) # 다더하면 0임

0.0


In [23]:
e = d**2   #더하면 0이기때문에 제곱해서 음수를 없애버림
print(e)

f = np.mean(e)    # 이것이 분산값
print(f)    


[[ 4.  9.  1.]
 [16.  1.  1.]]
5.333333333333333


In [24]:
np.var(a)  #  분산값 메서드

np.float64(5.333333333333333)

In [25]:
np.sqrt(f) # 분산 구한걸 루트를 씌운게 표준편차

np.float64(2.309401076758503)

In [26]:
i = np.std(a) #표준편차
print(i)

2.309401076758503


In [29]:
np.max(a,axis=0)  #행의 최대값 배열

array([8, 3, 3], dtype=int32)

In [31]:
np.min(a,axis=1)  #열의 최소값 배열

array([1, 3], dtype=int32)

In [36]:
print(a)

[[6 1 3]
 [8 3 3]]


In [37]:
np.argmax(a)  # 최대값 인덱스(0부터 시작해서 제일큰게 몇번째에)

3


In [34]:
np.argmin(a) # 만약에 같은 숫자가 나오면 앞에 인덱스를 띄움

np.int64(1)