In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,11,[2,3])
print(a)

[[9 1 4]
 [8 5 2]]


In [4]:
b = np.random.randint(1,11,[2,3])
print(b)

[[9 8 5]
 [5 6 9]]


교집합

In [ ]:
np.intersect1d(a,b) 

합집합

In [7]:
np.union1d(a,b)

array([1, 2, 4, 5, 6, 8, 9], dtype=int32)

차집합

In [8]:
np.setdiff1d(a,b)

array([1, 2, 4], dtype=int32)

a나 b 한쪽에만 있는

In [ ]:
np.setxor1d(a,b) 

중복제거

In [10]:
np.unique(a)

array([1, 2, 4, 5, 8, 9], dtype=int32)