In [13]:
import numpy as np

In [14]:
a = np.random.randint(1,101,[10])
print(a)

[47 55 85 74  3 12 31 96 94  1]


In [15]:
np.sort(a)

array([ 1,  3, 12, 31, 47, 55, 74, 85, 94, 96], dtype=int32)

In [16]:
np.sort(a)[::-1]

array([96, 94, 85, 74, 55, 47, 31, 12,  3,  1], dtype=int32)

In [19]:
d = np.random.randint(1,101,[3,5])
np.sort(d)  #행 별 정렬

array([[21, 27, 64, 75, 77],
       [ 1, 11, 45, 55, 89],
       [14, 26, 40, 44, 80]], dtype=int32)

In [92]:
# [np.sort(d[0])[::-1],
#  np.sort(d[1])[::-1],
#  np.sort(d[2])[::-1],
#  ]

arr = []
for row in d:
   k =np.sort(row)[::-1]
   obj_arr = np.array(k)
   arr.append(obj_arr)

print(arr)

[array([77, 75, 64, 27, 21], dtype=int32), array([89, 55, 45, 11,  1], dtype=int32), array([80, 44, 40, 26, 14], dtype=int32)]
