In [ ]:
# 2차원 -> 피타고라스 정리...
# 차원이 높아지면 거리 뭘로? =>유클리드 거리
# kNN자체가 유클리드거리

# 비행기 : 몇만단위, 게임 : 최대100, 아이스크림 : 최대2?
# 저대로 kNN하면 비행기만 크게 영향 끼칠 뿐 -> 동등하게 하려면
#   정규화 : 상수값 ->비율로 

In [ ]:
import os
print(" 현재 경로:", os.getcwd())
# 1. 파일이 있는 실제 경로를 복사해서 넣어주세요
target_path = "/mnt/batch/tasks/shared/LS_root/mounts/clusters/testcom0208/code/Users/student02_08/Jan26_1_MachineLearning"

# 2. 해당 경로로 작업 디렉토리 변경
os.chdir("target_path")

# 3. 변경된 경로 확인
print("변경된 현재 경로:", os.getcwd())



 현재 경로: /mnt/batch/tasks/shared/LS_root/mounts/clusters/student0208/code


FileNotFoundError: [Errno 2] No such file or directory: '/mnt/batch/tasks/shared/LS_root/mounts/clusters/testcom0208/code/Users/student02_08/Jan26_1_MachineLearning'

In [17]:
import numpy as np
import pandas as pd

df = pd.read_csv('./Users/student02_08/Jan26_1_MachineLearning/datingTestSet.txt', sep="\t", names=['비행기','게임','아이스크림','인기도'])

feature = df[['비행기','게임','아이스크림']].to_numpy()
label=df['인기도'].to_numpy()

print(feature)
print(label)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]
['인기많음' '보통' '별로' '별로' '별로' '별로' '인기많음' '인기많음' '별로' '인기많음' '별로' '별로' '보통'
 '별로' '별로' '별로' '별로' '별로' '보통' '인기많음' '보통' '별로' '보통' '인기많음' '보통' '인기많음'
 '보통' '인기많음' '보통' '별로' '인기많음' '별로' '인기많음' '별로' '보통' '별로' '별로' '보통' '인기많음'
 '인기많음' '별로' '보통' '인기많음' '인기많음' '인기많음' '별로' '별로' '별로' '별로' '보통' '보통' '별로'
 '인기많음' '보통' '보통' '보통' '보통' '인기많음' '별로' '보통' '별로' '보통' '보통' '보통' '보통' '보통'
 '인기많음' '보통' '인기많음' '별로' '보통' '인기많음' '보통' '보통' '별로' '인기많음' '별로' '별로'
 '인기많음' '인기많음' '별로' '보통' '인기많음' '별로' '인기많음' '별로' '보통' '보통' '별로' '별로'
 '인기많음' '인기많음' '별로' '보통' '별로' '인기많음' '인기많음' '보통' '별로' '별로' '인기많음' '별로'
 '보통' '인기많음' '인기많음' '보통' '인기많음' '인기많음' '별로' '보통' '인기많음' '보통' '별로' '인기많음'
 '별로' '보통' '별로' '별로' '보통' '인기많음' '보통' '인기많음' '보통' '인기많음' '보통' '별로' '인기많음'

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
feature = mm.fit_transform(feature) # 최대 최소 비율로 표현하게 변경

knc = KNeighborsClassifier(10) # 가장가까운 top10

knc.fit(feature,label)

,n_neighbors,10
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [24]:
airplane = float(input("비행기 :"))
game = float(input("게임 :"))
icecream = float(input("아이스크림 :"))

predictDate = np.array([[airplane,game,icecream]])

result = knc.predict(predictDate)[0]
print(result)


별로
